logging:
  level:
    io:
      spring:
        cloud:
          samples: INFO

management:
  security:
    enabled: false
  cloudfoundry:
    skip-ssl-validation: true

fortune:
  fallbackFortune: Your future is in Los Angeles baby!

